---
title: "Tables and figures"
format: html
tbl-colwidths: [75,25]
editor: visual
author: Andrew Laitha
table-of-contents: true
---

```{r}
#| label: load-packages
#| message: false

library(tidyverse)
library(ggthemes)
library(palmerpenguins)

```

1.  Create a 2 row x 2 column table, populate with a column for restaurant + column for cuisine. Then, cross reference it from text.

2.  Include the Quarto logo from the `images/` folder as a figure. Add a caption, id, and cross-reference to the figure.

3.  **Stretch goal:** Add a caption, label, and cross-reference to the figure generated from the code below.

@tbl-letters

| Restaurant | Cuisine |
|-----------:|--------:|
|    Italian |   Pizza |
|    Mexican |  Tortas |

: International restaurant and cuisine {#tbl-letters}

\`\`\`{python} #\| label: tbl-planets

See @quarto-logo for in the following. ! [Quarto logo](images/quarto-logo.png) {#fig-quarto-logo}

See @tbl-restaurant for international cuisine.

#\| warning: false #\| fig-width: 5 #\| fig-asp: 0.618

ggplot(data = penguins, mapping = aes(x = bill_length_mm, y = bill_depth_mm, color = species, shape = species)) + geom_point() + scale_color_colorblind() + labs(x = "Bill length (mm)", y = "Bill depth (mm)") + theme_minimal() \`\`\`
